#!/usr/bin/python3
''' Computes metrics from data generated by 0-generator.py '''
import sys
from collections import OrderedDict


def print_log(size, codes):
    ''' Prints computed metrics '''
    print("File size: {}".format(size))
    for k, v in codes.items():
        if k and v:
            print("{}: {}".format(k, v))


if __name__ == "__main__":
    line_count = total_size = 0
    CODES = [200, 301, 400, 401, 403, 404, 405, 500, None]
    codes = OrderedDict((k, 0) for k in CODES)
    try:
        for line in sys.stdin:
            tokens = line.split()
            status = tokens[-2] if len(tokens) > 1 else ''
            status = int(status) if status.isdigit() else None
            codes[status] += 1
            size = tokens[-1]
            total_size += int(size) if size.isdigit() else 0
            line_count += 1
            if line_count % 10 == 0:
                print_log(total_size, codes)
        print_log(total_size, codes)
    except KeyboardInterrupt:
        print_log(total_size, codes)
